#!/usr/bin/env python

import sys
from citrified_visualization import main

if __name__ == '__main__':
    if len(sys.argv) < 4 or len(sys.argv) > 5:
        print("usage: write_data_to_rosbag experiment fruit cut_quality [desired_run]")
    elif len(sys.argv) is 4:
        main(sys.argv[1], sys.argv[2], sys.argv[3])
    else:
        main(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[3])
